In [1]:
import pandas as pd
from astroquery.simbad import Simbad
from astropy.table import Table
from astroquery.vizier import Vizier

In [2]:
df = pd.DataFrame()

In [3]:
df = pd.read_excel('VSS SEB observed targets.xlsx', sheet_name='Data')

In [69]:
df.to_csv('original.csv', index=False)

In [4]:
df.head()

,Star,Epoch (HJD),Epoch Error,Period (d),Period Error,O-C Diagram Notes,Recommended Fequency,Last Observed
0,Ant S,2.458519e+06,0.000287,0.648348,2.959964e-07,linear?,yearly,2022-03-08 15:49:44.602
1,Aps DW,2.439210e+06,0.000787,2.312944,9.672835e-08,linear?,yearly,2022-05-09 14:58:03.446
2,Aps II,2.451931e+06,0.149860,0.842229,1.695586e-05,eccentric + apsidal motion?,2 per year,2021-06-23 10:19:15.616
3,Aps MR,2.457159e+06,0.000462,0.527864,1.404435e-07,linear?,yearly,2023-07-26 11:58:57.014
4,Aps NT,2.457208e+06,0.000361,0.294762,5.285139e-08,downward parabola?,yearly,2024-05-23 13:12:24.365

In [5]:
len(df)

214

In [6]:
df['Const', 'VarID'] = df['Star'].str.split()

In [7]:
object_names = []
for i in range(len(df)):
    details = df['Const', 'VarID'].iloc[i]
    if (len(details) == 2):
        object_name = details[1] +' '+ details[0]
    if (len(details) > 2):
        if (details[2].lower() == "secondary" or details[2].lower() == "primary"):
            object_name = details[1] +' '+ details[0]
        else:
            object_name = details[1]+details[2]# +' '+ details[0]
    object_names.append(object_name)

In [8]:
df['name'] = object_names

In [48]:
print(object_names)

['S Ant', 'DW Aps', 'II Aps', 'MR Aps', 'NT Aps', 'NX Aps', 'TV Aps', 'V0354 Aps', 'YY Aps', 'AO Aqr', 'DX Aqr', 'EE Aqr', 'FU Ara', 'R Ara', 'V0489 Ara', 'V0491 Ara', 'V0535 Ara', 'V0610 Ara', 'V0870 Ara', 'V0878 Ara', 'S Cae', 'TY Cap', 'OT Car', 'ST Car', 'V0454 Car', 'V0462 Car', 'V0625 Car', 'BG Cen', 'BH Cen', 'OZ Cen', 'RR Cen', 'V0676 Cen', 'V0701 Cen', 'V0716 Cen', 'V0752 Cen', 'V0757 Cen', 'V0758 Cen', 'V0759 Cen', 'V0831 Cen', 'V0901 Cen', 'V1129 Cen', 'V1362 Cen', 'AA Cet', 'TT Cet', 'WY Cet', 'GO Cha', 'RZ Cha', 'DM Cir', 'AR CMa', 'FQ CMa', 'TU CMa', 'VW CMa', 'ASASJ061717-3427.6', 'AZ Col', 'RU Col', 'eps CrA', 'V0711 CrA', 'V0731 CrA', 'V0734 CrA', 'TW Cru', 'ZZ Cru', 'AP Dor', 'RW Dor', 'BV Eri', 'CT Eri', 'YY Eri', 'XZ For', 'BC Gru', 'DY Gru', 'EH Gru', 'EN Gru', 'NSV25657', 'RV Gru', 'UV Gru', 'V Gru', 'YY Gru', 'SZ Hor', 'WY Hor', 'WZ Hor', 'CN Hyi', 'CP Hyi', 'CY Hyi', 'NSV1000', 'UV Hyi', 'BO Ind', 'BR Ind', 'CN Ind', 'CO Ind', 'CR Ind', 'CT Ind', 'CU Ind', 'DD Ind', 'ST Ind', 'TV Ind', 'RR Lep', 'FT Lup', 'GG Lup', 'GG Lup', 'IU Lup', 'OW Lup', 'QZ Lup', 'AU Men', 'NSV2569', 'RR Men', 'TY Men', 'TY Men', 'XY Men', 'XY Men', 'AH Mic', 'CY Mic', 'CZ Mic', 'DE Mic', 'DG Mic', 'DI Mic', 'BR Mus', 'BS Mus', 'eta Mus', 'TU Mus', 'TV Mus', 'TW Mus', 'V0395 Nor', 'V0398 Nor', 'EI Oct', 'EZ Oct', 'V1010 Oph', 'ER Ori', 'VV Ori', 'ASASSN-VJ184530.00-593235.0', 'BF Pav', 'HY Pav', 'IY Pav', 'KZ Pav', 'MW Pav', 'V0386 Pav', 'V0400 Pav', 'V0401 Pav', 'AD Phe', 'AE Phe', 'AU Phe', 'BL Phe', 'BM Phe', 'BQ Phe', 'CT Phe', 'NSV455', 'YZ Phe', 'XZ PsA', 'ZZ PsA', 'CS Pup', 'GY Pup', 'GZ Pup', 'HI Pup', 'NO Pup', 'NO Pup', 'V0410 Pup', 'V0621 Pup', 'V0653 Pup', 'CR Pyx', 'NSV1389', 'UX Ret', 'BB Scl', 'CP Scl', 'CW Scl', 'CX Scl', 'RT Scl', 'UY Scl', 'V0462 Sco', 'V0632 Sco', 'V0638 Sco', 'V0701 Sco', 'V0760 Sco', 'V0883 Sco', 'V0954 Sco', 'V1055 Sco', 'V1084 Sco', 'CV Sex', 'VY Sex', 'XX Sex', 'RS Sgr', 'V0505 Sgr', 'V0779 Sgr', 'V2509 Sgr', 'V3792 Sgr', 'V3863 Sgr', 'V4197 Sgr', 'GY Tel', 'QW Tel', 'V0343 Tel', 'V0368 Tel', 'EQ TrA', 'GN TrA', 'GQ TrA', 'HP TrA', 'MN TrA', 'MN TrA', 'NT TrA', 'NT TrA', 'V0336 TrA', 'AQ Tuc', 'CU Tuc', 'DX Tuc', 'EK Tuc', 'NSV14537', 'BF Vel', 'BU Vel', 'DU Vel', 'FM Vel', 'QX Vel', 'TT Vel', 'V0362 Vel', 'V0448 Vel', 'HW Vir', 'AE Vol', 'AF Vol', 'W Vol']

In [70]:
vizier = Vizier()
object_info2 = Vizier(catalog='B/gcvs/gcvs_cat', columns=['VarName', 'RAJ2000', 'DEJ2000', 'magMax','Period', 'VarType', 'SpType']).query_constraints(GCVS=object_names)[0]

WARNING: MergeConflictWarning: Cannot merge meta key 'null' types <class 'float'> and <class 'float'>, choosing null=nan [astropy.utils.metadata]

In [71]:
object_info2

<Table length=206>
 VarName    RAJ2000     DEJ2000    magMax      Period      VarType SpType
                                    mag          d
  str11      str11       str11    float32     float64       str10  str17
--------- ----------- ----------- ------- ---------------- ------- ------
S     Ant 09 32 18.39 -28 37 40.0   6.270     0.6483489000      EW    F3V
DW    Aps 17 23 30.03 -67 55 44.9   8.860     2.3129485000      EA  B6III
II    Aps 16 27 41.91 -74 50 44.3  10.900     0.8422536000      EB
MR    Aps 17 07 57.54 -73 43 35.4  10.580     0.5278636000      EB
NT    Aps 14 42 42.57 -74 18 41.6   8.200     0.2947648000      EW G3/G5V
NX    Aps 14 56 41.79 -75 19 04.2  11.060     0.4092282000     EW:     Fp
TV    Aps 14 45 49.71 -71 17 39.7  13.800     0.6474930000      EW
V0354 Aps 15 15 28.58 -77 46 42.3  12.350     0.5871530000      EA
YY    Aps 15 02 34.32 -72 45 10.8  11.340     0.8555520000      EB
      ...         ...         ...     ...              ...     ...    ...
DU    Vel 09 45 42.13 -49 13 30.2  10.800     1.5525630000      EA
FM    Vel 09 47 42.27 -53 28 10.6  12.200     0.3895262000   EW/KW
QX    Vel 09 48 56.54 -47 54 45.0   7.980               --      EB
TT    Vel 10 20 16.47 -46 14 04.4  10.500     2.1083805000  EA/SD:     A5
V0362 Vel 11 04 20.99 -46 03 30.5   9.090               --      EW
V0448 Vel 08 24 55.49 -48 33 34.8  11.630     0.3648750000      EW
HW    Vir 12 44 20.24 -08 40 16.9  10.500               --    EA/D
AE    Vol 08 45 39.40 -64 59 28.1   9.970     0.4066140000      EW
AF    Vol 08 53 34.86 -70 28 07.6  10.600     0.6389400000      EW
W     Vol 07 37 40.05 -69 32 32.4  10.900     2.7583610000  EA/AR:    K/M

In [54]:
franco = Simbad.query_objects(object_names)

WARNING: BlankResponseWarning: Warning: The script line number 74 raised an error (recorded in the `errors` attribute of the result table): Identifier not found in the database : NSV 25657  [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 160 raised an error (recorded in the `errors` attribute of the result table): Identifier not found in the database : NSV  1389 [astroquery.simbad.core]

In [66]:
franco

<Table length=211>
  MAIN_ID         RA           DEC      ...     COO_BIBCODE     SCRIPT_NUMBER_ID
               "h:m:s"       "d:m:s"    ...
   object       str13         str13     ...        object            int32
----------- ------------- ------------- ... ------------------- ----------------
   V* S Ant 09 32 18.3864 -28 37 39.968 ... 2020yCat.1350....0G                1
  V* DW Aps 17 23 30.0309 -67 55 44.906 ... 2020yCat.1350....0G                2
  V* II Aps 16 27 41.9350 -74 50 44.229 ... 2020yCat.1350....0G                3
  V* MR Aps 17 07 57.5281 -73 43 35.400 ... 2020yCat.1350....0G                4
  HD 128575 14 42 42.5763 -74 18 41.568 ... 2020yCat.1350....0G                5
  V* NX Aps 14 56 41.7970 -75 19 04.205 ... 2020yCat.1350....0G                6
  V* TV Aps 14 45 49.6502 -71 17 39.742 ... 2020yCat.1350....0G                7
V* V354 Aps 15 15 28.5827 -77 46 42.253 ... 2020yCat.1350....0G                8
  V* YY Aps 15 02 34.3399 -72 45 10.678 ... 2020yCat.1350....0G                9
        ...           ...           ... ...                 ...              ...
  V* DU Vel 09 45 42.1289 -49 13 30.202 ... 2020yCat.1350....0G              205
  V* FM Vel 09 47 42.2651 -53 28 10.587 ... 2020yCat.1350....0G              206
  V* QX Vel 09 48 56.5347 -47 54 44.949 ... 2020yCat.1350....0G              207
  V* TT Vel 10 20 16.4605 -46 14 04.437 ... 2020yCat.1350....0G              208
V* V362 Vel 11 04 20.9889 -46 03 30.529 ... 2020yCat.1350....0G              209
V* V448 Vel 08 24 55.4977 -48 33 34.971 ... 2020yCat.1350....0G              210
BD-07  3477 12 44 20.2386 -08 40 16.846 ... 2020yCat.1350....0G              211
  V* AE Vol 08 45 39.4033 -64 59 28.043 ... 2020yCat.1350....0G              212
  V* AF Vol 08 53 34.8637 -70 28 07.633 ... 2020yCat.1350....0G              213
   V* W Vol 07 37 40.0546 -69 32 32.383 ... 2020yCat.1350....0G              214

In [10]:
object_info2

<Table length=206>
 VarName    RAJ2000     DEJ2000    magMax      Period      VarType SpType
                                    mag          d
  str11      str11       str11    float32     float64       str10  str17
--------- ----------- ----------- ------- ---------------- ------- ------
S     Ant 09 32 18.39 -28 37 40.0   6.270     0.6483489000      EW    F3V
DW    Aps 17 23 30.03 -67 55 44.9   8.860     2.3129485000      EA  B6III
II    Aps 16 27 41.91 -74 50 44.3  10.900     0.8422536000      EB
MR    Aps 17 07 57.54 -73 43 35.4  10.580     0.5278636000      EB
NT    Aps 14 42 42.57 -74 18 41.6   8.200     0.2947648000      EW G3/G5V
NX    Aps 14 56 41.79 -75 19 04.2  11.060     0.4092282000     EW:     Fp
TV    Aps 14 45 49.71 -71 17 39.7  13.800     0.6474930000      EW
V0354 Aps 15 15 28.58 -77 46 42.3  12.350     0.5871530000      EA
YY    Aps 15 02 34.32 -72 45 10.8  11.340     0.8555520000      EB
      ...         ...         ...     ...              ...     ...    ...
DU    Vel 09 45 42.13 -49 13 30.2  10.800     1.5525630000      EA
FM    Vel 09 47 42.27 -53 28 10.6  12.200     0.3895262000   EW/KW
QX    Vel 09 48 56.54 -47 54 45.0   7.980               --      EB
TT    Vel 10 20 16.47 -46 14 04.4  10.500     2.1083805000  EA/SD:     A5
V0362 Vel 11 04 20.99 -46 03 30.5   9.090               --      EW
V0448 Vel 08 24 55.49 -48 33 34.8  11.630     0.3648750000      EW
HW    Vir 12 44 20.24 -08 40 16.9  10.500               --    EA/D
AE    Vol 08 45 39.40 -64 59 28.1   9.970     0.4066140000      EW
AF    Vol 08 53 34.86 -70 28 07.6  10.600     0.6389400000      EW
W     Vol 07 37 40.05 -69 32 32.4  10.900     2.7583610000  EA/AR:    K/M

In [11]:
df

,Star,Epoch (HJD),Epoch Error,Period (d),Period Error,O-C Diagram Notes,Recommended Fequency,Last Observed,"(Const, VarID)",name
0,Ant S,2.458519e+06,0.000287,0.648348,2.959964e-07,linear?,yearly,2022-03-08 15:49:44.602,"[Ant, S]",S Ant
1,Aps DW,2.439210e+06,0.000787,2.312944,9.672835e-08,linear?,yearly,2022-05-09 14:58:03.446,"[Aps, DW]",DW Aps
2,Aps II,2.451931e+06,0.149860,0.842229,1.695586e-05,eccentric + apsidal motion?,2 per year,2021-06-23 10:19:15.616,"[Aps, II]",II Aps
3,Aps MR,2.457159e+06,0.000462,0.527864,1.404435e-07,linear?,yearly,2023-07-26 11:58:57.014,"[Aps, MR]",MR Aps
4,Aps NT,2.457208e+06,0.000361,0.294762,5.285139e-08,downward parabola?,yearly,2024-05-23 13:12:24.365,"[Aps, NT]",NT Aps
...,...,...,...,...,...,...,...,...,...,...
209,Vel V0448,2.451868e+06,NaN,0.364876,NaN,only two ToMs,yearly,2021-03-04 14:09:17.856,"[Vel, V0448]",V0448 Vel
210,Vir HW,2.452500e+06,0.000190,0.116720,3.396294e-09,linear?,yearly,2023-06-24 11:18:51.638,"[Vir, HW]",HW Vir
211,Vol AE,2.452614e+06,0.000285,0.406615,1.940033e-08,linear?,yearly,2022-12-28 13:18:28.541,"[Vol, AE]",AE Vol
212,Vol AF,2.452618e+06,0.000565,0.638935,6.027154e-08,linear?,yearly,2023-01-18 12:52:15.456,"[Vol, AF]",AF Vol
213,Vol W,2.458356e+06,0.000434,2.758150,2.988410e-06,downward parabola?,yearly,2020-03-12 15:03:07.402,"[Vol, W]",W Vol

In [12]:
gcvs_cat_df = object_info2.to_pandas()

In [ ]:
gcvs_cat_df

In [13]:
gcvs_cat_df.head()

     VarName      RAJ2000      DEJ2000  magMax    Period VarType  SpType
0  S     Ant  09 32 18.39  -28 37 40.0    6.27  0.648349      EW     F3V
1  DW    Aps  17 23 30.03  -67 55 44.9    8.86  2.312949      EA   B6III
2  II    Aps  16 27 41.91  -74 50 44.3   10.90  0.842254      EB
3  MR    Aps  17 07 57.54  -73 43 35.4   10.58  0.527864      EB
4  NT    Aps  14 42 42.57  -74 18 41.6    8.20  0.294765      EW  G3/G5V

In [47]:
df[df['name'].str.contains('AS')]

,Star,Epoch (HJD),Epoch Error,Period (d),Period Error,O-C Diagram Notes,Recommended Fequency,Last Observed,"(Const, VarID)",name
52,Col ASAS J061717-3427.6,2.451869e+06,0.003481,0.534486,3.621299e-07,linear?,yearly,2018-02-27 11:38:58.474,"[Col, ASAS, J061717-3427.6]",ASASJ061717-3427.6
127,Pav ASASSN-V J184530.00-593235.0,2.458711e+06,0.001910,8.150840,NaN,only one ToM measured,yearly,2019-08-15 15:05:16.310,"[Pav, ASASSN-V, J184530.00-593235.0]",ASASSN-VJ184530.00-593235.0

In [14]:
gcvs_cat_df['VarName'] = gcvs_cat_df['VarName'].str.replace(r'\s+', ' ', regex=True)
result_df = df.merge(gcvs_cat_df, left_on='name', right_on="VarName", how='left')

In [15]:
result_df = result_df.drop_duplicates(subset=['VarName', 'Star'])

In [16]:
CONS = result_df['name'].str.split().str.get(1)
starname = result_df['name'].str.split().str.get(0)

In [17]:
result_df = result_df.assign(CONS=CONS)
result_df = result_df.assign(starname=starname)

In [18]:
result_df.columns

Index([                'Star',          'Epoch (HJD)',          'Epoch Error',
                 'Period (d)',         'Period Error',    'O-C Diagram Notes',
       'Recommended Fequency',        'Last Observed',     ('Const', 'VarID'),
                       'name',              'VarName',              'RAJ2000',
                    'DEJ2000',               'magMax',               'Period',
                    'VarType',               'SpType',                 'CONS',
                   'starname'],
      dtype='object')

Now to build the dataframe that contains the data we want

In [19]:
ephem_df = pd.DataFrame()

In [20]:
ephem_df = ephem_df.assign(CONS=result_df['CONS'])
ephem_df = ephem_df.assign(NAME=result_df['starname'])
ephem_df['PS'] = "p"
ephem_df['PS'].loc[result_df['Star'].str.contains('Primary')] = "p"
ephem_df['PS'].loc[result_df['Star'].str.contains('Secondary')] = "s"

In [21]:
ephem_df['RATING'] = 10

In [22]:
ephem_df = ephem_df.assign(RA2000=result_df['RAJ2000'].str.replace(' ', '').str.slice(0, -1))

In [23]:
ephem_df = ephem_df.assign(DE2000=result_df['DEJ2000'].str.replace(' ', '').str.slice(0, -2))

In [24]:
ephem_df = ephem_df.assign(M0=result_df['Epoch (HJD)']- 2400000.5)

In [25]:
ephem_df = ephem_df.assign(PER=result_df['Period (d)'])

In [26]:
ephem_df = ephem_df.assign(MAX=result_df['magMax'])

In [27]:
ephem_df = ephem_df.assign(PRIM=result_df['magMax'])

In [28]:
ephem_df = ephem_df.assign(SEK=result_df['magMax'])

In [29]:
ephem_df['BRANCH'] = 'V'
ephem_df['LD'] = ''
ephem_df['SD'] = ''
ephem_df['GSC'] = ''
ephem_df = ephem_df.assign(TYPE=result_df['VarType'])
ephem_df['N10'] = '1'
ephem_df['N'] = '1'

In [30]:
ephem_df

,CONS,NAME,PS,RATING,RA2000,DE2000,M0,PER,MAX,PRIM,SEK,BRANCH,LD,SD,GSC,TYPE,N10,N
0,Ant,S,p,10,093218.3,-283740,58518.209393,0.648348,6.27,6.27,6.27,V,,,,EW,1,1
1,Aps,DW,p,10,172330.0,-675544,39209.001941,2.312944,8.86,8.86,8.86,V,,,,EA,1,1
2,Aps,II,p,10,162741.9,-745044,51930.911585,0.842229,10.90,10.90,10.90,V,,,,EB,1,1
3,Aps,MR,p,10,170757.5,-734335,57158.510010,0.527864,10.58,10.58,10.58,V,,,,EB,1,1
4,Aps,NT,p,10,144242.5,-741841,57207.635624,0.294762,8.20,8.20,8.20,V,,,,EW,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,Vel,V0448,p,10,082455.4,-483334,51867.680000,0.364876,11.63,11.63,11.63,V,,,,EW,1,1
222,Vir,HW,p,10,124420.2,-084016,52499.555234,0.116720,10.50,10.50,10.50,V,,,,EA/D,1,1
223,Vol,AE,p,10,084539.4,-645928,52613.131000,0.406615,9.97,9.97,9.97,V,,,,EW,1,1
224,Vol,AF,p,10,085334.8,-702807,52617.343002,0.638935,10.60,10.60,10.60,V,,,,EW,1,1
225,Vol,W,p,10,073740.0,-693232,58355.210597,2.758150,10.90,10.90,10.90,V,,,,EA/AR:,1,1

In [31]:
# Define column formatters
formatters = {
    'CONS': '{:6}'.format,  
    'NAME': '{:<17}'.format,  
    'PS': '{:<3}'.format,
    'RATING': '{:<7}'.format,  
    'RA2000': '{:<9}'.format,  
    'DE2000': '{:<8}'.format,
    'M0': '{:<13}'.format,  
    'PER': '{:<13}'.format,  
    'MAX': '{:<9}'.format,
    'PRIM': '{:<9}'.format,  
    'SEK': '{:<9}'.format,  
    'BRANCH': '{:<7}'.format,
    'LD': '{:<5}'.format,  
    'SD': '{:<5}'.format,
    'GSC': '{:<12}'.format,  
    'TYPE': '{:<13}'.format,
    'N10': '{:<7}'.format,  
    'N': '{:<7}'.format,
}

In [32]:
ephem_file = " CONS NAME             PS RATING RA2000   DE2000  M0           PER          MAX      PRIM     SEK      BRANCH LD   SD   GSC         TYPE         N10    N"
for i in range(0, len(ephem_df)):
    ephem_file += "\n"
    ephem_file += f' {ephem_df.iloc[i].CONS}  {ephem_df.iloc[i].NAME.ljust(16)} {ephem_df.iloc[i].PS.ljust(3)}'
    ephem_file += f'{str(ephem_df.iloc[i].RATING).ljust(6)} {str(ephem_df.iloc[i].RA2000).ljust(8)} {str(ephem_df.iloc[i].DE2000).ljust(7)}'
    ephem_file += f' {str("{:12.6f}".format(ephem_df.iloc[i].M0)).ljust(12)} {str("{:11.9f}".format(ephem_df.iloc[i].PER)).ljust(12)} {str(ephem_df.iloc[i].MAX).ljust(8)}'
    ephem_file += f' {str(ephem_df.iloc[i].MAX).ljust(8)}' #PRIM
    ephem_file += f' {str(ephem_df.iloc[i].MAX).ljust(8)}' #SEK
    ephem_file += f' {str(ephem_df.iloc[i].BRANCH).ljust(6)}' #BRANCH
    ephem_file += f' {str(ephem_df.iloc[i].LD).ljust(4)}' #LD
    ephem_file += f' {str(ephem_df.iloc[i].SD).ljust(4)}' #SD
    ephem_file += f' {str(ephem_df.iloc[i].GSC).ljust(11)}' #GSC
    ephem_file += f' {str(ephem_df.iloc[i].TYPE).ljust(12)}' #TYPE
    ephem_file += f' {str(ephem_df.iloc[i].N10).ljust(6)}' 
    ephem_file += f' {str(ephem_df.iloc[i].N).ljust(6)}'

In [33]:
with open('output.dat', 'w') as file:
    # Write the string to the file
    file.write(ephem_file)

In [34]:
print(s)

NameError: name 's' is not defined

In [ ]:
# Write to fixed-width format file
with open('output.dat', 'w') as f:
    ephem_df.to_string(f, index=False, formatters=formatters)

In [ ]:
############# TO DO the PS col needs to be filled!!!!!

In [ ]:
# Write the DataFrame to a file with fixed column widths
with open('output.txt', 'w') as f:
    # Write the header
    f.write(format_row(ephem_df.columns, column_widths) + '\n')
    # Write each row
    for _, row in ephem_df.iterrows():
        f.write(format_row(row, column_widths) + '\n')

In [ ]:
final_df

In [ ]:
result_df

In [ ]:
print(gcvs_cat_df['VarName'][0])

In [ ]:
gcvs_cat_df['VarName'] = gcvs_cat_df['VarName'].str.replace(r'\s+', ' ', regex=True)

In [ ]:
print(gcvs_cat_df['VarName'][0])