In [63]:
import pandas as pd
from astroquery.simbad import Simbad
from astropy.table import Table
from astroquery.vizier import Vizier
import re

In [2]:
df = pd.DataFrame()

In [4]:
df = pd.read_excel('VSS SEB observed targets.xlsx', sheet_name='Data')

In [5]:
df.to_csv('original.csv', index=False)

In [6]:
df.head()

,Star,Epoch (HJD),Epoch Error,Period (d),Period Error,O-C Diagram Notes,Recommended Fequency,Last Observed
0,Ant S,2.458519e+06,0.000287,0.648348,2.959964e-07,linear?,yearly,2022-03-08 15:49:44.602
1,Aps DW,2.439210e+06,0.000787,2.312944,9.672835e-08,linear?,yearly,2022-05-09 14:58:03.446
2,Aps II,2.451931e+06,0.149860,0.842229,1.695586e-05,eccentric + apsidal motion?,2 per year,2021-06-23 10:19:15.616
3,Aps MR,2.457159e+06,0.000462,0.527864,1.404435e-07,linear?,yearly,2023-07-26 11:58:57.014
4,Aps NT,2.457208e+06,0.000361,0.294762,5.285139e-08,downward parabola?,yearly,2024-05-23 13:12:24.365

In [7]:
len(df)

214

In [8]:
df['Const', 'VarID'] = df['Star'].str.split()

In [9]:
object_names = []
for i in range(len(df)):
    details = df['Const', 'VarID'].iloc[i]
    if (len(details) == 2):
        object_name = details[1] +' '+ details[0]
    if (len(details) > 2):
        if (details[2].lower() == "secondary" or details[2].lower() == "primary"):
            object_name = details[1] +' '+ details[0]
        else:
            object_name = details[1]+details[2]# +' '+ details[0]
    object_names.append(object_name)

In [10]:
df['name'] = object_names

In [46]:
df['SCRIPT_NUMBER_ID'] = df.index

In [11]:
print(object_names)

['S Ant', 'DW Aps', 'II Aps', 'MR Aps', 'NT Aps', 'NX Aps', 'TV Aps', 'V0354 Aps', 'YY Aps', 'AO Aqr', 'DX Aqr', 'EE Aqr', 'FU Ara', 'R Ara', 'V0489 Ara', 'V0491 Ara', 'V0535 Ara', 'V0610 Ara', 'V0870 Ara', 'V0878 Ara', 'S Cae', 'TY Cap', 'OT Car', 'ST Car', 'V0454 Car', 'V0462 Car', 'V0625 Car', 'BG Cen', 'BH Cen', 'OZ Cen', 'RR Cen', 'V0676 Cen', 'V0701 Cen', 'V0716 Cen', 'V0752 Cen', 'V0757 Cen', 'V0758 Cen', 'V0759 Cen', 'V0831 Cen', 'V0901 Cen', 'V1129 Cen', 'V1362 Cen', 'AA Cet', 'TT Cet', 'WY Cet', 'GO Cha', 'RZ Cha', 'DM Cir', 'AR CMa', 'FQ CMa', 'TU CMa', 'VW CMa', 'ASASJ061717-3427.6', 'AZ Col', 'RU Col', 'eps CrA', 'V0711 CrA', 'V0731 CrA', 'V0734 CrA', 'TW Cru', 'ZZ Cru', 'AP Dor', 'RW Dor', 'BV Eri', 'CT Eri', 'YY Eri', 'XZ For', 'BC Gru', 'DY Gru', 'EH Gru', 'EN Gru', 'NSV25657', 'RV Gru', 'UV Gru', 'V Gru', 'YY Gru', 'SZ Hor', 'WY Hor', 'WZ Hor', 'CN Hyi', 'CP Hyi', 'CY Hyi', 'NSV1000', 'UV Hyi', 'BO Ind', 'BR Ind', 'CN Ind', 'CO Ind', 'CR Ind', 'CT Ind', 'CU Ind', 'DD Ind', 'ST Ind', 'TV Ind', 'RR Lep', 'FT Lup', 'GG Lup', 'GG Lup', 'IU Lup', 'OW Lup', 'QZ Lup', 'AU Men', 'NSV2569', 'RR Men', 'TY Men', 'TY Men', 'XY Men', 'XY Men', 'AH Mic', 'CY Mic', 'CZ Mic', 'DE Mic', 'DG Mic', 'DI Mic', 'BR Mus', 'BS Mus', 'eta Mus', 'TU Mus', 'TV Mus', 'TW Mus', 'V0395 Nor', 'V0398 Nor', 'EI Oct', 'EZ Oct', 'V1010 Oph', 'ER Ori', 'VV Ori', 'ASASSN-VJ184530.00-593235.0', 'BF Pav', 'HY Pav', 'IY Pav', 'KZ Pav', 'MW Pav', 'V0386 Pav', 'V0400 Pav', 'V0401 Pav', 'AD Phe', 'AE Phe', 'AU Phe', 'BL Phe', 'BM Phe', 'BQ Phe', 'CT Phe', 'NSV455', 'YZ Phe', 'XZ PsA', 'ZZ PsA', 'CS Pup', 'GY Pup', 'GZ Pup', 'HI Pup', 'NO Pup', 'NO Pup', 'V0410 Pup', 'V0621 Pup', 'V0653 Pup', 'CR Pyx', 'NSV1389', 'UX Ret', 'BB Scl', 'CP Scl', 'CW Scl', 'CX Scl', 'RT Scl', 'UY Scl', 'V0462 Sco', 'V0632 Sco', 'V0638 Sco', 'V0701 Sco', 'V0760 Sco', 'V0883 Sco', 'V0954 Sco', 'V1055 Sco', 'V1084 Sco', 'CV Sex', 'VY Sex', 'XX Sex', 'RS Sgr', 'V0505 Sgr', 'V0779 Sgr', 'V2509 Sgr', 'V3792 Sgr', 'V3863 Sgr', 'V4197 Sgr', 'GY Tel', 'QW Tel', 'V0343 Tel', 'V0368 Tel', 'EQ TrA', 'GN TrA', 'GQ TrA', 'HP TrA', 'MN TrA', 'MN TrA', 'NT TrA', 'NT TrA', 'V0336 TrA', 'AQ Tuc', 'CU Tuc', 'DX Tuc', 'EK Tuc', 'NSV14537', 'BF Vel', 'BU Vel', 'DU Vel', 'FM Vel', 'QX Vel', 'TT Vel', 'V0362 Vel', 'V0448 Vel', 'HW Vir', 'AE Vol', 'AF Vol', 'W Vol']

In [50]:
vizier = Vizier()
gcvs_info = Vizier(catalog='B/gcvs/gcvs_cat').query_constraints(GCVS=object_names)[0]

In [51]:
gcvs_info

<Table length=206>
   GCVS   n_GCVS   RAJ2000     DEJ2000   VarType  magMax      Period      SpType Exists  VarName  Simbad
                                                   mag          d
  str10    str1     str11       str11     str10  float32     float64      str17  str12    str11    str6
--------- ------ ----------- ----------- ------- ------- ---------------- ------ ------ --------- ------
    S Ant      x 09 32 18.39 -28 37 40.0      EW   6.270     0.6483489000    F3V        S     Ant Simbad
   DW Aps      x 17 23 30.03 -67 55 44.9      EA   8.860     2.3129485000  B6III        DW    Aps Simbad
   II Aps      x 16 27 41.91 -74 50 44.3      EB  10.900     0.8422536000               II    Aps Simbad
   MR Aps      x 17 07 57.54 -73 43 35.4      EB  10.580     0.5278636000               MR    Aps Simbad
   NT Aps      x 14 42 42.57 -74 18 41.6      EW   8.200     0.2947648000 G3/G5V        NT    Aps Simbad
   NX Aps      x 14 56 41.79 -75 19 04.2     EW:  11.060     0.4092282000     Fp        NX    Aps Simbad
   TV Aps      x 14 45 49.71 -71 17 39.7      EW  13.800     0.6474930000               TV    Aps Simbad
V0354 Aps      x 15 15 28.58 -77 46 42.3      EA  12.350     0.5871530000               V0354 Aps Simbad
   YY Aps      x 15 02 34.32 -72 45 10.8      EB  11.340     0.8555520000               YY    Aps Simbad
   AO Aqr      x 22 11 31.90 -22 47 16.5      EW  11.040     0.4893432000     F:        AO    Aqr Simbad
   DX Aqr      * 22 02 26.25 -16 57 53.4      EA   6.430     0.9450106000    A2V        DX    Aqr Simbad
   EE Aqr      x 22 34 41.97 -19 51 35.3      EB   7.910     0.5089958200    F0V        EE    Aqr Simbad
      ...    ...         ...         ...     ...     ...              ...    ...    ...       ...    ...
   BF Vel      * 08 56 27.03 -39 58 36.0   EA/SD  11.400     0.7040200000               BF    Vel Simbad
   BU Vel      * 08 40 06.29 -42 49 43.3      EW  10.490     0.5162856000     F0        BU    Vel Simbad
   DU Vel      x 09 45 42.13 -49 13 30.2      EA  10.800     1.5525630000               DU    Vel Simbad
   FM Vel      * 09 47 42.27 -53 28 10.6   EW/KW  12.200     0.3895262000               FM    Vel Simbad
   QX Vel      x 09 48 56.54 -47 54 45.0      EB   7.980               --               QX    Vel Simbad
   TT Vel      * 10 20 16.47 -46 14 04.4  EA/SD:  10.500     2.1083805000     A5        TT    Vel Simbad
V0362 Vel      x 11 04 20.99 -46 03 30.5      EW   9.090               --               V0362 Vel Simbad
V0448 Vel      * 08 24 55.49 -48 33 34.8      EW  11.630     0.3648750000               V0448 Vel Simbad
   HW Vir      x 12 44 20.24 -08 40 16.9    EA/D  10.500               --               HW    Vir Simbad
   AE Vol      x 08 45 39.40 -64 59 28.1      EW   9.970     0.4066140000               AE    Vol Simbad
   AF Vol      x 08 53 34.86 -70 28 07.6      EW  10.600     0.6389400000               AF    Vol Simbad
    W Vol      x 07 37 40.05 -69 32 32.4  EA/AR:  10.900     2.7583610000    K/M        W     Vol Simbad

In [33]:
simbad_info = Simbad.query_objects(object_names)

WARNING: BlankResponseWarning: Warning: The script line number 74 raised an error (recorded in the `errors` attribute of the result table): Identifier not found in the database : NSV 25657  [astroquery.simbad.core]
WARNING: BlankResponseWarning: Warning: The script line number 160 raised an error (recorded in the `errors` attribute of the result table): Identifier not found in the database : NSV  1389 [astroquery.simbad.core]

In [43]:
simbad_df = simbad_info.to_pandas()

In [44]:
simbad_df

,MAIN_ID,RA,DEC,RA_PREC,DEC_PREC,COO_ERR_MAJA,COO_ERR_MINA,COO_ERR_ANGLE,COO_QUAL,COO_WAVELENGTH,COO_BIBCODE,SCRIPT_NUMBER_ID
0,V* S Ant,09 32 18.3864,-28 37 39.968,14,14,0.0125,0.0141,90,A,O,2020yCat.1350....0G,1
1,V* DW Aps,17 23 30.0309,-67 55 44.906,14,14,0.0115,0.0162,90,A,O,2020yCat.1350....0G,2
2,V* II Aps,16 27 41.9350,-74 50 44.229,14,14,0.0086,0.0098,90,A,O,2020yCat.1350....0G,3
3,V* MR Aps,17 07 57.5281,-73 43 35.400,14,14,0.2043,0.2315,90,A,O,2020yCat.1350....0G,4
4,HD 128575,14 42 42.5763,-74 18 41.568,14,14,0.0113,0.0119,90,A,O,2020yCat.1350....0G,5
...,...,...,...,...,...,...,...,...,...,...,...,...
206,V* V448 Vel,08 24 55.4977,-48 33 34.971,14,14,0.0093,0.0119,90,A,O,2020yCat.1350....0G,210
207,BD-07 3477,12 44 20.2386,-08 40 16.846,14,14,0.0545,0.0266,90,A,O,2020yCat.1350....0G,211
208,V* AE Vol,08 45 39.4033,-64 59 28.043,14,14,0.0098,0.0114,90,A,O,2020yCat.1350....0G,212
209,V* AF Vol,08 53 34.8637,-70 28 07.633,14,14,0.0319,0.0326,90,A,O,2020yCat.1350....0G,213
210,V* W Vol,07 37 40.0546,-69 32 32.383,14,14,0.0110,0.0109,90,A,O,2020yCat.1350....0G,214

In [45]:
gcvs_df = gcvs_info.to_pandas()

In [48]:
gcvs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   VarName  206 non-null    object
 1   RAJ2000  206 non-null    object
 2   DEJ2000  206 non-null    object
 3   magMax   206 non-null    float32
 4   Period   171 non-null    float64
 5   VarType  206 non-null    object
 6   SpType   206 non-null    object
dtypes: float32(1), float64(1), object(5)
memory usage: 10.6+ KB

In [65]:
def replace_extra_spaces(text):
    return re.sub(r'\s+', ' ', text).strip()

gcvs_df['VarName'] = gcvs_df['VarName'].apply(replace_extra_spaces)

In [66]:
part1=pd.merge(df, simbad_df, on='SCRIPT_NUMBER_ID', how='left')

In [119]:
result_df = pd.merge(part1, gcvs_df, left_on='name', right_on='VarName', how='left')

In [120]:
result_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Star                  226 non-null    object
 1   Epoch (HJD)           226 non-null    float64
 2   Epoch Error           213 non-null    float64
 3   Period (d)            226 non-null    float64
 4   Period Error          212 non-null    float64
 5   O-C Diagram Notes     226 non-null    object
 6   Recommended Fequency  226 non-null    object
 7   Last Observed         226 non-null    datetime64[ns]
 8   (Const, VarID)        226 non-null    object
 9   name                  226 non-null    object
 10  SCRIPT_NUMBER_ID      226 non-null    int64
 11  MAIN_ID               222 non-null    object
 12  RA                    222 non-null    object
 13  DEC                   222 non-null    object
 14  RA_PREC               222 non-null    float64
 15  DEC_PREC              222 non-null    float64
 16  COO_ERR_MAJA          222 non-null    float32
 17  COO_ERR_MINA          222 non-null    float32
 18  COO_ERR_ANGLE         222 non-null    float64
 19  COO_QUAL              222 non-null    object
 20  COO_WAVELENGTH        222 non-null    object
 21  COO_BIBCODE           222 non-null    object
 22  VarName               218 non-null    object
 23  RAJ2000               218 non-null    object
 24  DEJ2000               218 non-null    object
 25  magMax                218 non-null    float32
 26  Period                181 non-null    float64
 27  VarType               218 non-null    object
 28  SpType                218 non-null    object
dtypes: datetime64[ns](1), float32(3), float64(8), int64(1), object(16)
memory usage: 48.7+ KB

In [121]:
result_df['CONS'] = result_df[('Const', 'VarID')].apply(lambda x: x[0])

<hr>

Now to build the dataframe that contains the data we want

In [122]:
ephem_df = pd.DataFrame()

In [123]:
ephem_df = ephem_df.assign(CONS=result_df['CONS'])
ephem_df = ephem_df.assign(NAME=result_df['Star'])
ephem_df['PS'] = "p"
ephem_df['PS'].loc[result_df['Star'].str.contains('Primary')] = "p"
ephem_df['PS'].loc[result_df['Star'].str.contains('Secondary')] = "s"

C:\Users\adminuser\AppData\Local\Temp\2\ipykernel_10712\3187912084.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ephem_df['PS'].loc[result_df['Star'].str.contains('Primary')] = "p"
C:\Users\adminuser\AppData\Local\Temp\2\ipykernel_10712\3187912084.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  ephem_df['PS'].loc[result_df['Star'].str.contains('Secondary')] = "s"

In [124]:
ephem_df['RATING'] = 10

In [125]:
ephem_df = ephem_df.assign(RA2000=result_df['RA'].str.replace(' ', '').str.slice(0, -1))

In [126]:
ephem_df = ephem_df.assign(DE2000=result_df['DEC'].str.replace(' ', '').str.slice(0, -2))

In [127]:
ephem_df = ephem_df.assign(M0=result_df['Epoch (HJD)']- 2400000.5)

In [128]:
ephem_df = ephem_df.assign(PER=result_df['Period (d)'])

In [129]:
ephem_df = ephem_df.assign(MAX=result_df['magMax'])

In [130]:
ephem_df = ephem_df.assign(PRIM=result_df['magMax'])

In [131]:
ephem_df = ephem_df.assign(SEK=result_df['magMax'])

In [132]:
ephem_df['BRANCH'] = 'V'
ephem_df['LD'] = ''
ephem_df['SD'] = ''
ephem_df['GSC'] = ''
ephem_df = ephem_df.assign(TYPE=result_df['VarType'])
ephem_df['N10'] = '1'
ephem_df['N'] = '1'

In [133]:
ephem_df

,CONS,NAME,PS,RATING,RA2000,DE2000,M0,PER,MAX,PRIM,SEK,BRANCH,LD,SD,GSC,TYPE,N10,N
0,Ant,Ant S,p,10,NaN,NaN,58518.209393,0.648348,6.27,6.27,6.27,V,,,,EW,1,1
1,Aps,Aps DW,p,10,093218.386,-283739.9,39209.001941,2.312944,8.86,8.86,8.86,V,,,,EA,1,1
2,Aps,Aps II,p,10,172330.030,-675544.9,51930.911585,0.842229,10.90,10.90,10.90,V,,,,EB,1,1
3,Aps,Aps MR,p,10,162741.935,-745044.2,57158.510010,0.527864,10.58,10.58,10.58,V,,,,EB,1,1
4,Aps,Aps NT,p,10,170757.528,-734335.4,57207.635624,0.294762,8.20,8.20,8.20,V,,,,EW,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,Vel,Vel V0448,p,10,110420.988,-460330.5,51867.680000,0.364876,11.63,11.63,11.63,V,,,,EW,1,1
222,Vir,Vir HW,p,10,082455.497,-483334.9,52499.555234,0.116720,10.50,10.50,10.50,V,,,,EA/D,1,1
223,Vol,Vol AE,p,10,124420.238,-084016.8,52613.131000,0.406615,9.97,9.97,9.97,V,,,,EW,1,1
224,Vol,Vol AF,p,10,084539.403,-645928.0,52617.343002,0.638935,10.60,10.60,10.60,V,,,,EW,1,1
225,Vol,Vol W,p,10,085334.863,-702807.6,58355.210597,2.758150,10.90,10.90,10.90,V,,,,EA/AR:,1,1

In [ ]:
# Define column formatters
formatters = {
    'CONS': '{:6}'.format,  
    'NAME': '{:<17}'.format,  
    'PS': '{:<3}'.format,
    'RATING': '{:<7}'.format,  
    'RA2000': '{:<9}'.format,  
    'DE2000': '{:<8}'.format,
    'M0': '{:<13}'.format,  
    'PER': '{:<13}'.format,  
    'MAX': '{:<9}'.format,
    'PRIM': '{:<9}'.format,  
    'SEK': '{:<9}'.format,  
    'BRANCH': '{:<7}'.format,
    'LD': '{:<5}'.format,  
    'SD': '{:<5}'.format,
    'GSC': '{:<12}'.format,  
    'TYPE': '{:<13}'.format,
    'N10': '{:<7}'.format,  
    'N': '{:<7}'.format,
}

In [134]:
ephem_file = " CONS NAME             PS RATING RA2000   DE2000  M0           PER          MAX      PRIM     SEK      BRANCH LD   SD   GSC         TYPE         N10    N"
for i in range(0, len(ephem_df)):
    ephem_file += "\n"
    ephem_file += f' {ephem_df.iloc[i].CONS}  {ephem_df.iloc[i].NAME.ljust(16)} {ephem_df.iloc[i].PS.ljust(3)}'
    ephem_file += f'{str(ephem_df.iloc[i].RATING).ljust(6)} {str(ephem_df.iloc[i].RA2000).ljust(8)} {str(ephem_df.iloc[i].DE2000).ljust(7)}'
    ephem_file += f' {str("{:12.6f}".format(ephem_df.iloc[i].M0)).ljust(12)} {str("{:11.9f}".format(ephem_df.iloc[i].PER)).ljust(12)} {str(ephem_df.iloc[i].MAX).ljust(8)}'
    ephem_file += f' {str(ephem_df.iloc[i].MAX).ljust(8)}' #PRIM
    ephem_file += f' {str(ephem_df.iloc[i].MAX).ljust(8)}' #SEK
    ephem_file += f' {str(ephem_df.iloc[i].BRANCH).ljust(6)}' #BRANCH
    ephem_file += f' {str(ephem_df.iloc[i].LD).ljust(4)}' #LD
    ephem_file += f' {str(ephem_df.iloc[i].SD).ljust(4)}' #SD
    ephem_file += f' {str(ephem_df.iloc[i].GSC).ljust(11)}' #GSC
    ephem_file += f' {str(ephem_df.iloc[i].TYPE).ljust(12)}' #TYPE
    ephem_file += f' {str(ephem_df.iloc[i].N10).ljust(6)}' 
    ephem_file += f' {str(ephem_df.iloc[i].N).ljust(6)}'

In [135]:
with open('output.dat', 'w') as file:
    # Write the string to the file
    file.write(ephem_file)

<hr>